import type { Store } from "./types";

export const DEFAULT_STORE: Store = {
  settings: {
    hero: {
      title: "BLASS",
      subtitle: "Iluminação & Componentes",
      image: "",
      banners: [],
    },
    about: {
      paragraphs: [
        "Desde o início, nosso caminho foi construir **soluções com qualidade**, identidade própria, guiadas por **técnica, evolução e visão de futuro**.",
        "Fundada por **Marcos Verona** em Flores da Cunha, Rio Grande do Sul, a empresa cresceu de com empenho em atendimento pós-venda excepcional e eficiência na entrega de toda sua linha de produtos.",
        "Ao longo de **mais de duas décadas**, evoluímos constantemente, acompanhando as tendências do mercado e criando soluções que transformam e otimizam ambientes!",
      ],
    },
    stats: { years: "26", resellers: "2.000+", coverage: "Atendemos todo o brasil" },
    highlight: {
      tag: "DESTAQUE",
      title: "Novidade",
      subtitle: "Fita COB 3mm",
      body:
        "A tecnologia e o acabamento da fita COB são soluções que vieram para elevar o padrão da iluminação nos projetos!\n\nCom espessura reduzida, proporciona uma aplicação mais discreta e integrada ao móvel, sem interferir no design. Sua luz contínua elimina a marcação dos pontos de LED, garantindo um efeito mais uniforme, limpo e visualmente sofisticado. Versátil, pode ser aplicada com ou sem perfil, adaptando-se a diferentes necessidades de projeto.\n\nEm comparação com fitas tradicionais, oferece um resultado mais sutil e refinado. Ideal para quem busca praticidade na aplicação e excelência no acabamento. Transforme a iluminação em um diferencial que valoriza cada detalhe do ambiente",
      image: "",
    },
    categoriesIntro: {
      title: "",
      subtitle: "",
    },
    tagline: {
      line1: "Qualidade que",
      highlight1: "ilumina projetos",
      line2: "e",
      highlight2: "transforma ambientes.",
      ctaLabel: "Confira as soluções disponíveis!",
      ctaHref: "/produtos",
      image: "",
    },
    reach: {
      title: "ESTAMOS PRESENTES EM QUASE 2000 REVENDAS",
      body: "Ou seja: não importa onde você está, a Blass estará por perto, mostrando que é possível fazer diferente.",
      ctaLabel: "QUERO COMPRAR",
      ctaHref: "#contato",
    },
    visibility: {
      stats: true,
      tagline: true,
      highlight: true,
      reach: true,
    },
    seo: {
      head: "",
      bodyStart: "",
    },
    layouts: {
      construimos: {
        predioZoom: 1.15,
        mao: { x: 80, y: 52, w: 54 },
        brilho: { x: 72, y: 92, w: 60 },
      },
    },
    inovacao: {
      images: ["/novo/carrossel.webp"],
    },
    galeria: {
      images: [
        "/novo/galeria-1.webp",
        "/novo/galeria-2.webp",
        "/novo/galeria-3.webp",
        "/novo/galeria-4.webp",
        "/novo/galeria-5.webp",
      ],
    },
    pills: {
      words: [
        "FITAS DE LED",
        "PERFIS PARA LED",
        "LUMINÁRIAS",
        "FONTES E DRIVERS",
        "ACIONADORES",
        "DIFUSORES",
        "CABIDEIROS",
        "PUXADORES",
        "SUPORTES",
        "TÁBUAS DE PASSAR",
        "TRAVA PORTA",
        "GRADE FORNO",
      ],
    },
    tendencias: {
      text: "A **Blass** não nasceu para seguir as tendências…",
      highlight: "Nasceu para criá-las!",
      image: "/novo/tendencias-fundo.webp",
    },
    categoriasCards: {
      cards: [
        { label: "ILUMINAÇÃO", href: "/produtos?cat=iluminacao", off: "/novo/cat-iluminacao-off.webp", on: "/novo/cat-iluminacao-on.webp" },
        { label: "COMPONENTES", href: "/produtos?cat=componentes", off: "/novo/cat-componentes-off.webp", on: "/novo/cat-componentes-on.webp" },
        { label: "ACESSÓRIOS", href: "/produtos?cat=acessorios", off: "/novo/cat-acessorios-off.webp", on: "/novo/cat-acessorios-on.webp" },
      ],
    },
    contact: {
      phone: "(54) 3022-9600",
      phoneDigits: "5430229600",
      email: "sac@blass.ind.br",
      address: "Rua Milano, 1804 — Flores da Cunha — RS, 95270-000",
      instagram: "https://instagram.com/blassiluminacao",
      facebook: "https://facebook.com/blassiluminacao",
      linkedin: "https://linkedin.com/company/blass",
    },
  },
  categories: [
    {
      slug: "iluminacao",
      name: "Iluminação",
      description: "Você cria o projeto, nós oferecemos as mais modernas soluções em iluminação e decoração.",
      icon: "lamp",
      subcategories: [
        { slug: "fitas-de-led", name: "Fitas de LED" },
        { slug: "luminarias-pontuais", name: "Luminárias pontuais" },
        { slug: "fontes-e-drivers", name: "Fontes e drivers" },
        { slug: "acionamentos", name: "Acionamentos" },
        { slug: "acessorios", name: "Acessórios" },
        { slug: "perfis-para-led", name: "Perfis para LED" },
        { slug: "cabideiros-iluminados", name: "Cabideiros iluminados" },
      ],
    },
    {
      slug: "componentes",
      name: "Componentes e Acessórios",
      description: "Acabamentos diferenciados e uma ampla variedade de acessórios para todos os ambientes.",
      icon: "wrench",
      subcategories: [
        { slug: "desempenadores-de-portas", name: "Desempenadores de portas" },
        { slug: "suportes-para-tubo-cabideiro", name: "Suportes para tubo cabideiro" },
        { slug: "tubo-para-cabideiro", name: "Tubo para cabideiro" },
        { slug: "puxadores", name: "Puxadores" },
        { slug: "tabuas-de-passar", name: "Tábuas de passar" },
        { slug: "suporte-para-prateleira-fendas", name: "Suporte para prateleira — Fendas" },
        { slug: "suporte-para-prateleira-tucanos", name: "Suporte para prateleira — Tucanos" },
        { slug: "suporte-para-prateleira-mao-francesa", name: "Suporte para prateleira — Mão francesa" },
        { slug: "suporte-para-prateleira-invisiveis", name: "Suporte para prateleira — Invisíveis" },
        { slug: "acessorios", name: "Acessórios" },
        { slug: "trava-porta", name: "Trava porta" },
        { slug: "grade-forno", name: "Grade forno" },
      ],
    },
  ],
  products: [
    {
      id: "p1",
      slug: "fita-cob-3mm",
      name: "Fita COB 3mm",
      category: "iluminacao",
      subcategory: "fitas-de-led",
      shortDescription: "Iluminação contínua, ultra discreta. Ideal para móveis planejados.",
      description:
        "Fita COB de 3 mm de espessura, luz contínua sem pontos de LED visíveis. Acabamento sofisticado para móveis e ambientes residenciais e comerciais.",
      image: "/images/products/fita-cob.jpg",
      featured: true,
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "p2",
      slug: "perfil-aluminio-embutir",
      name: "Perfil de Alumínio Embutir",
      category: "iluminacao",
      subcategory: "perfis-para-led",
      shortDescription: "Perfil de embutir para acabamento profissional em fitas LED.",
      image: "/images/products/perfil.jpg",
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "p3",
      slug: "puxador-cava-alumino",
      name: "Puxador Cava Alumínio",
      category: "componentes",
      subcategory: "puxadores",
      shortDescription: "Puxador cava em alumínio anodizado, design minimalista.",
      image: "/images/products/puxador.jpg",
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "p4",
      slug: "suporte-prateleira-invisivel",
      name: "Suporte Prateleira Invisível",
      category: "componentes",
      subcategory: "suporte-para-prateleira-invisiveis",
      shortDescription: "Suporte oculto para prateleiras de madeira. Acabamento limpo.",
      image: "/images/products/suporte-invisivel.jpg",
      published: true,
      createdAt: new Date().toISOString(),
    },
  ],
  blogCategories: [
    { slug: "iluminacao", name: "Iluminação" },
    { slug: "projetos", name: "Projetos" },
    { slug: "tendencias", name: "Tendências" },
  ],
  blogPosts: [
    {
      id: "b1",
      slug: "fita-cob-revoluciona-iluminacao",
      title: "Fita COB: a evolução da iluminação em móveis planejados",
      excerpt: "Entenda por que a tecnologia COB virou padrão de acabamento em projetos sofisticados.",
      body:
        "A fita COB (Chip on Board) traz luz contínua, sem pontos visíveis. Esse acabamento se tornou referência para marcenarias e arquitetos que buscam um visual mais limpo nos projetos de iluminação indireta.\n\nNeste post, exploramos os principais cenários de aplicação.",
      coverImage: "/images/blog/cob.jpg",
      category: "iluminacao",
      published: true,
      publishedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: "b2",
      slug: "5-tendencias-iluminacao-2026",
      title: "5 tendências de iluminação para 2026",
      excerpt: "Da temperatura de cor ajustável aos perfis embutidos: o que dominará projetos no próximo ano.",
      body: "Conteúdo de exemplo.",
      category: "tendencias",
      published: true,
      publishedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  ],
};
